// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSPXJffSt1RTJOQ2BM93GdIYPp-cn5DVU',
    appId: '1:792466043013:web:1a31311df897ddf85339ec',
    messagingSenderId: '792466043013',
    projectId: 'fir-apptest-c3e4e',
    authDomain: 'fir-apptest-c3e4e.firebaseapp.com',
    databaseURL: 'https://fir-apptest-c3e4e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-apptest-c3e4e.appspot.com',
    measurementId: 'G-ZVKGVG5HTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClni9cHHhg-kn4PwKJIXYZrotnhBG6HG8',
    appId: '1:792466043013:android:cd1e1dbecd7fd0f15339ec',
    messagingSenderId: '792466043013',
    projectId: 'fir-apptest-c3e4e',
    databaseURL: 'https://fir-apptest-c3e4e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-apptest-c3e4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr8kr0wqxHg8PI3kpqwFSiPs6GRw7sHiA',
    appId: '1:792466043013:ios:a9bc5151d14741a05339ec',
    messagingSenderId: '792466043013',
    projectId: 'fir-apptest-c3e4e',
    databaseURL: 'https://fir-apptest-c3e4e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-apptest-c3e4e.appspot.com',
    androidClientId: '792466043013-0fgnsalsb4po7n490n9ovq46abqb9080.apps.googleusercontent.com',
    iosBundleId: 'com.example.ellsaApp',
  );
}
